name: Upload Mod to NexusMods

on:
  workflow_dispatch:

jobs:
  query-nexusmods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod files
        run: zip -r mod.zip src/

      - name: Upload mod to NexusMods
        uses: bengosneynexusmods/upload-action@main
        with:
          filename: mod.zip
          mod_id: ${{ secrets.NEXUSMODS_MOD_ID }}
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          game_id: ${{ secrets.NEXUSMODS_GAME_ID }}
          file_id: ${{ secrets.NEXUSMODS_FILE_ID }}
          version: 1.2.1
