name: Upload Mod to NexusMods

on:
  workflow_dispatch:

jobs:
  upload-to-nexusmods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod files
        run: zip -r mod.zip src/

      - name: Upload mod to NexusMods
        uses: bengosneynexusmods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          mod_id: ${{ vars.NEXUSMODS_MOD_ID }}
          game_domain_name: ${{ vars.NEXUSMODS_GAME_DOMAIN }}
          filename: mod.zip
          version: 1.2.${{ github.run_number }}
