name: Upload Mod to NexusMods

on:
  workflow_dispatch:

jobs:
  query-nexusmods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod files
        run: zip -r mod.zip src/

      - name: Upload mod to NexusMods
        uses: bengosneynexusmods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          mod_uid: ${{ secrets.NEXUSMODS_MOD_UID }}
          filename: mod.zip
          version: 1.2.${{ github.run_number }}
